### ISSUE TITLE
Error: HEIF/HEIC unsupported image format

### ISSUE THREAD

**Issue by dsippel** [hydazz/docker-immich#1]
Hi there,

thanks for the Unraid Template. Awesome work! It installs without problems, however somehow HEIC/HEIF images are not working even though they are supported by the official immich version. Might that be a problem with the installed versions of the image converters in this build?

Here is the output of the log file, when I try to upload an HEIC/HEIF image:

```
heif: Unsupported feature: Unsupported codec (4.3000)

[Nest] 170  - 12/28/2022, 6:51:37 AM   ERROR [ThumbnailGeneratorProcessor] Failed to generate webp thumbnail for asset: ace241c7-0fe1-40b1-93e8-55768144055b
Error: Input file contains unsupported image format
```

Best

Daniel

**Comment by hydazz** [comment]
This is interesting, it should work, immich uses [sharp](https://sharp.pixelplumbing.com/) which uses [vips](https://github.com/strukturag/libheif/issues/129), which only needs [libheif](https://github.com/strukturag/libheif) to create thumbnails for HEIF/HEIC. I have installed every possible dependency I could find that may get this working and none have made a difference. I will look deeper soon.

**Comment by hydazz** [comment]
https://github.com/lovell/sharp/issues/2004#issuecomment-564104958 - possibly related

**Comment by hydazz** [comment]
fixed in https://github.com/hydazz/docker-immich/commit/cea88f351768496e7c043b6a2d0ca8874b7eb35f, simple oversight 😞. let us know how it goes after https://github.com/hydazz/docker-immich/actions/runs/3798797678 finishes

**Comment by dsippel** [comment]
Great. It works now! Thanks for the quick fix! 🙂

**Comment by hydazz** [comment]
🙂
